### ISSUE TITLE
Cannot teleport or destroy the NPC

### ISSUE THREAD

**Issue by FunkyFight** [DanielTheDev/NPC#4] opened 2022-04-13 07:56 UTC
Hi!

Firstly, I want to tell you that your project is really cool! The problem is, I can't teleport or destroy a NPC.
I'm using a simple code of creation instruction, waiting (with BukkitRunnable) then teleportation/destroy instructions.

```java
if(args[0].equalsIgnoreCase("test2")) {
                NPC test = new NPC(p.getLocation(), "test");
                test.spawnNPC(p);

                new BukkitRunnable() {
                    @Override
                    public void run() {
                        test.destroyNPC(p);
                        p.sendMessage("§a§lDESTROYED");
                    }
                }.runTaskLater(EldarothPlayer.instance, 20*3);
            }
```

The NPC is created, but that's it. When I'm destroying it, I get this error:

`[09:50:09 WARN]: [EldarothPlayer] Task #26 for EldarothPlayer v1.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'
        at io.github.danielthedev.npc.NPC.getEntityDestroyPacket(NPC.java:319) ~[ELDAROTHPLUGIN-1.0-SNAPSHOT-shaded.jar:?]
        at io.github.danielthedev.npc.NPC.destroyNPC(NPC.java:113) ~[ELDAROTHPLUGIN-1.0-SNAPSHOT-shaded.jar:?]
        at me.funkyfight.eldarothplayer.commands.DebugCommand$1.run(DebugCommand.java:93) ~[ELDAROTHPLUGIN-1.0-SNAPSHOT-shaded.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-400]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-400]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-400]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-400]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-400]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-400]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-400]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Line 93 in the stacktrace refer to the .destroyNPC(player) method**

**Comment by DanielTheDev** [comment] 2022-04-14 12:51
Yes, I am aware of that problem. 
Firstly, due to changes from 1.17 to 1.17.1 the constructor PacketPlayOutEntityDestroy is now changed.
Therefore, you should import the github gist file and compile my util class yourself.

Secondly, the teleport bug was caused by the call order of the packets Teleport and Rotate head. 
That has also been fixed in the update gist if I recall correctly. 

Here is the link to the resource [Gist](https://gist.github.com/DanielTheDev/a9d91a6ee1b43f17994a040b2fce9fb1)

**Comment by FunkyFight** [comment] 2022-04-17 16:17
Thanks you!

**Closed as completed** 2022-04-17 17:57 UTC
